#!/bin/bash

set -e
set -u
set -x

INSTANCE_NAME="props"

cd /opt/codedeploy-agent/deployment-root/${DEPLOYMENT_GROUP_ID}/${DEPLOYMENT_ID}/deployment-archive

set -a
source ./codedeploy/parameters
set +a

echo "copying envs"

aws s3 cp s3://props-production-app-bucket/shared/secrets.env.txt ./secrets-prod.env

echo "setting envs"

for envvar in $(cat ./secrets-prod.env); do
  export $envvar;
done

printenv APP_DOMAIN

echo "done setting envs"

$(aws ecr get-login --region=eu-central-1 --no-include-email)

COMPOSE="docker-compose -p ${INSTANCE_NAME} -f ./docker-compose-production.yml"

${COMPOSE} up -d
${COMPOSE} run --rm web bundle exec rake assets:precompile
${COMPOSE} run --rm web bundle exec rake db:migrate

# Remove unused data, do not prompt for confirmation
docker image prune -f