export const RECEIVE_USER_PROPS = 'RECEIVE_USER_PROPS';
export const RECEIVE_USER_GIVEN_PROPS = 'RECEIVE_USER_GIVEN_PROPS';
export const RECEIVE_USER = 'RECEIVE_USER';
export const RECEIVE_USERS = 'RECEIVE_USERS';

export const REQUEST_USER_PROPS = 'REQUEST_USER_PROPS';
export const REQUEST_USER_GIVEN_PROPS = 'REQUEST_USER_GIVEN_PROPS';
export const REQUEST_USER = 'REQUEST_USER';
export const REQUEST_USERS = 'REQUEST_USERS';
