export const CHANGE_THANKS_TEXT = 'CHANGE_THANKS_TEXT';
export const RECEIVE_PROPS = 'RECEIVE_PROPS';
export const REQUEST_PROPS = 'REQUEST_PROPS';
export const RECEIVE_USER_PROPS = 'RECEIVE_USER_PROPS';
export const RECEIVE_USER_GIVEN_PROPS = 'RECEIVE_USER_GIVEN_PROPS';
export const RECEIVE_USER = 'RECEIVE_USER';
export const RECEIVE_USERS = 'RECEIVE_USERS';

export const REQUEST_USER_PROPS = 'REQUEST_USER_PROPS';
export const REQUEST_USER_GIVEN_PROPS = 'REQUEST_USER_GIVEN_PROPS';
export const REQUEST_USER = 'REQUEST_USER';
export const REQUEST_USERS = 'REQUEST_USERS';
export const SET_USERS_FILTER = 'SET_USERS_FILTER';
export const SELECT_USERS = 'SELECT_USERS';
export const PROP_CREATED = 'PROP_CREATED';
export const PROP_CREATION_ERRORS = 'PROP_CREATION_ERROR';
export const PROP_CREATION_REQUEST = 'PROP_CREATION_REQUEST';
