export const RECEIVE_USERS = 'RECEIVE_USERS';
export const SET_USERS_QUERY = 'SET_USERS_QUERY';
export const REQUEST_USER_PROFILE = 'REQUEST_USER_PROFILE';
export const RECEIVE_USER_PROFILE = 'RECEIVE_USER_PROFILE';
