module Users
  class Auth0Service
    def initialize(user_params)
      @user = user_params
    end

    attr_reader :user

    def auth(fields = 'email,identities')
      # TO CHANGE
      auth0_params = {
        client_id: 'MB4eZDiH9hQRpJ5IoXvbOtXgslTk5bAn',
        token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik1EUkZSamM0TURjM01URTJOVUk1T1RORE1qTTFNelJHT1RWRk0wTkNNalEwTVRBM1JUazFPQSJ9.eyJpc3MiOiJodHRwczovL2ZpaWkuZXUuYXV0aDAuY29tLyIsInN1YiI6Ik1CNGVaRGlIOWhRUnBKNUlvWHZiT3RYZ3NsVGs1YkFuQGNsaWVudHMiLCJhdWQiOiJodHRwczovL2ZpaWkuZXUuYXV0aDAuY29tL2FwaS92Mi8iLCJleHAiOjE0ODcxNjc3MzcsImlhdCI6MTQ4NzA4MTMzNywic2NvcGUiOiJyZWFkOmNsaWVudF9ncmFudHMgY3JlYXRlOmNsaWVudF9ncmFudHMgZGVsZXRlOmNsaWVudF9ncmFudHMgdXBkYXRlOmNsaWVudF9ncmFudHMgcmVhZDp1c2VycyB1cGRhdGU6dXNlcnMgZGVsZXRlOnVzZXJzIGNyZWF0ZTp1c2VycyByZWFkOnVzZXJzX2FwcF9tZXRhZGF0YSB1cGRhdGU6dXNlcnNfYXBwX21ldGFkYXRhIGRlbGV0ZTp1c2Vyc19hcHBfbWV0YWRhdGEgY3JlYXRlOnVzZXJzX2FwcF9tZXRhZGF0YSBjcmVhdGU6dXNlcl90aWNrZXRzIHJlYWQ6Y2xpZW50cyB1cGRhdGU6Y2xpZW50cyBkZWxldGU6Y2xpZW50cyBjcmVhdGU6Y2xpZW50cyByZWFkOmNsaWVudF9rZXlzIHVwZGF0ZTpjbGllbnRfa2V5cyBkZWxldGU6Y2xpZW50X2tleXMgY3JlYXRlOmNsaWVudF9rZXlzIHJlYWQ6Y29ubmVjdGlvbnMgdXBkYXRlOmNvbm5lY3Rpb25zIGRlbGV0ZTpjb25uZWN0aW9ucyBjcmVhdGU6Y29ubmVjdGlvbnMgcmVhZDpyZXNvdXJjZV9zZXJ2ZXJzIHVwZGF0ZTpyZXNvdXJjZV9zZXJ2ZXJzIGRlbGV0ZTpyZXNvdXJjZV9zZXJ2ZXJzIGNyZWF0ZTpyZXNvdXJjZV9zZXJ2ZXJzIHJlYWQ6ZGV2aWNlX2NyZWRlbnRpYWxzIHVwZGF0ZTpkZXZpY2VfY3JlZGVudGlhbHMgZGVsZXRlOmRldmljZV9jcmVkZW50aWFscyBjcmVhdGU6ZGV2aWNlX2NyZWRlbnRpYWxzIHJlYWQ6cnVsZXMgdXBkYXRlOnJ1bGVzIGRlbGV0ZTpydWxlcyBjcmVhdGU6cnVsZXMgcmVhZDplbWFpbF9wcm92aWRlciB1cGRhdGU6ZW1haWxfcHJvdmlkZXIgZGVsZXRlOmVtYWlsX3Byb3ZpZGVyIGNyZWF0ZTplbWFpbF9wcm92aWRlciBibGFja2xpc3Q6dG9rZW5zIHJlYWQ6c3RhdHMgcmVhZDp0ZW5hbnRfc2V0dGluZ3MgdXBkYXRlOnRlbmFudF9zZXR0aW5ncyByZWFkOmxvZ3MgcmVhZDpzaGllbGRzIGNyZWF0ZTpzaGllbGRzIGRlbGV0ZTpzaGllbGRzIHJlYWQ6Z3JhbnRzIGRlbGV0ZTpncmFudHMgcmVhZDpndWFyZGlhbl9mYWN0b3JzIHVwZGF0ZTpndWFyZGlhbl9mYWN0b3JzIHJlYWQ6Z3VhcmRpYW5fZW5yb2xsbWVudHMgZGVsZXRlOmd1YXJkaWFuX2Vucm9sbG1lbnRzIGNyZWF0ZTpndWFyZGlhbl9lbnJvbGxtZW50X3RpY2tldHMifQ.1jjjjNm24VZnCcKl9f6eIA6quVli0eqNPf4VLH8lFX31G_hasSaG29nfwmtTwKzHlEYjCxWpDZAHFwPBsAYjKLHz911UfSe4gDnrNlQPBoo0xwcCYnj1ht6QdFGwOesQiOyqTapKeWSEcUXy9yg-siK2Px5C89w1hgklsmIfBKaqYo-fxbkP26RHut1K19SixXv9J48z2aZ-iWAQ5MQjje9Wb3w_jNZ2m0k0E9aiKYRU28htkCpYD82tdmgcYo2VcZ5Idx3bVdRjXWkW8AqEFh5k9ifVHflhSyXbLH35EZ77f8GAaGWga8lZ3APYZIPMJQlq89281vDNCuDA-uJTsA',
        domain: 'fiii.eu.auth0.com',
        api_version: 2,
      }

      auth0 = Auth0Client.new(auth0_params)
      provider_uid = user.provider + '|' + user.uid
      check_user!(auth0.user(provider_uid, fields: fields))
    end

    def check_user!(auth0_user)
      auth0_user['email'] == user['info']['email'] &&
        auth0_user['identities'][0]['user_id'] == user.uid
    end
  end
end
