require 'capistrano/setup'
require 'capistrano/deploy'
require 'capistrano/scm/git'
install_plugin Capistrano::SCM::Git

require 'capose'

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob('capistrano/tasks/*.rake').each { |r| import r }
