#!/bin/bash

# During this deployment lifecycle event, the AWS CodeDeploy agent
# copies the application revision files to a temporary location:
# /opt/codedeploy-agent/deployment-root/deployment-group-id/deployment-id/deployment-archive

# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html
# supported variables set by the CodeDeploy agent:
# APPLICATION_NAME
# DEPLOYMENT_ID
# DEPLOYMENT_GROUP_NAME
# DEPLOYMENT_GROUP_ID
# LIFECYCLE_EVENT

# Exit immediately if a pipeline [...] returns a non-zero status.
set -e
# Treat unset variables and parameters [...] as an error when performing parameter expansion (substituting).
set -u
# Print a trace of simple commands
set -x

# env
# pwd

# EC2s are configured with instance profile (a specific role) and all the required policies.

# Replace "your_instance_name" with name of your instance
INSTANCE_NAME="props"
DOCKER_REPO="124027903148.dkr.ecr.eu-central-1.amazonaws.com/calluna-ecr-props-staging"
# Environment variables retrieved from System Manager / Parameter Store (configured with Calluna)
REGION=$(curl -s 169.254.169.254/latest/dynamic/instance-identity/document | jq -r ".region")
VARS=$(aws --region $REGION ssm get-parameters-by-path --recursive --path /calluna/${INSTANCE_NAME}/staging --with-decryption | jq -r '.Parameters | .[] | .Name + "=" + .Value' | sed -e s#/calluna/${INSTANCE_NAME}/staging/##g)
rm -rf /opt/secrets.env
for envvar in ${VARS}; do
  echo $envvar >> /opt/secrets.env;
done
cd /opt/codedeploy-agent/deployment-root/${DEPLOYMENT_GROUP_ID}/${DEPLOYMENT_ID}/deployment-archive
export IMAGE= ${DOCKER_REPO}:${DEPLOYMENT_ID}
        ## build and push image
docker build -t ${DOCKER_REPO}:${DEPLOYMENT_ID} -f docker/staging/Dockerfile .

COMPOSE="docker-compose -p ${INSTANCE_NAME} -f docker-compose-staging.yml"
${COMPOSE} run --rm web bundle exec rake assets:precompile
${COMPOSE} run --rm web bundle exec rake db:migrate
${COMPOSE} up -d
# Remove unused data, do not prompt for confirmation
docker image prune -f