#!/bin/bash

# Treat unset variables and parameters [...] as an error when performing parameter expansion (substituting).
set -u
# Print a trace of simple commands
set -x

DIR=$(cat /opt/codedeploy-agent/deployment-root/deployment-instructions/${DEPLOYMENT_GROUP_ID}_most_recent_install)
cd $DIR/deployment-archive/

COMPOSE="docker-compose -p props-be -f docker-compose-staging.yml"


${COMPOSE} down | true

# NOTE:
#   ${COMPOSE} down | true
#   should always return an RC zero in order to avoid the ApplicationStop Hook failures; it's fairly safe and very simple.